# 2022 Stefan Beller
version: '3.8'
services:
  postgres:
    image: postgres:14.4
    volumes:
      - ./volume_postges:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: fhv
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadmin
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volume_mongo:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbadmin
      MONGO_INITDB_ROOT_PASSWORD: dbadmin
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbadmin
      ME_CONFIG_MONGODB_URL: mongodb://dbadmin:dbadmin@mongo:27017/
  redis:
    image: redis:6.2-alpine
    # image: redislabs/rejson:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - ./volume_redis:/data
  neo4j:
    image: arm64v8/neo4j
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./volume_neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/streams
      NEO4J_dbms_logs_debug_level: DEBUG